openapi: "3.0.0"
info:
  title: Portal DWH Service API
  version: "1.0"
  description: Service that provides data from DWH to the Portal
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: /api/v1
security:
  - apiKey: []
paths:
  /healthcheck:
    get:
      tags:
        - "system"
      summary: Check the health of the service.
      responses:
        "200":
          description: The service is healthy.
        "503":
          description: The service is not healthy.

  /analytics/relays/aggregated/{category}:
    get:
      tags:
        - "user"
      summary: Relays analytics retrieve aggregated values of a chosen metric category between selected dates.
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: category_value
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: category
          in: path
          required: true
          description: The category of a metric to get insights of.
          schema:
            type: string
            enum:
              - account_id
              - application_id

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          $ref: "#/components/responses/NotFound"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /analytics/relays/daily/{category}:
    get:
      tags:
        - "user"
      summary: Relays analytics retrieve aggregated values of a chosen metric category between selected dates.
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: category_value
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: category
          in: path
          required: true
          description: The category of a metric to get insights of.
          schema:
            type: string
            enum:
              - account_id
              - application_id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          $ref: "#/components/responses/NotFound"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /analytics/relays/{category}:
    get:
      tags:
        - "user"
      summary: Relays analytics retrieve aggregated values of a chosen metric category between selected dates.
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: category
          in: path
          required: true
          description: The category of a metric to get insights of.
          schema:
            type: string
            enum:
              - transactions
              - errors
        - name: account_id
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
        - name: portal_application_id
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: chain_id
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: chain_method
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          $ref: "#/components/responses/NotFound"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /logs:
    get:
      tags:
        - "user"
      summary: Retrieve application error messages by given timestamp range.
      parameters:
        - name: portal_application_id
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "204":
          description: No content
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          $ref: "#/components/responses/Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          $ref: "#/components/responses/NotFound"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  responses:
    Unauthorized:
      description: Unauthorized request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  securitySchemes:
    apiKey:
      type: apiKey
      name: Portal-DWH-Service-Api-Key
      in: header

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    AnalyticsRelaysAggregated:
      type: object
      properties:
        date:
          type: string
          format: date
        category_value:
          type: string
        rate_success:
          type: number
          format: float
        rate_error:
          type: number
          format: float
        count_total:
          type: integer
        avg_latency:
          type: number
          format: float

    AnalyticsRelaysDaily:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        category_value:
          type: string
        rate_success:
          type: number
          format: float
        rate_error:
          type: number
          format: float
        count_total:
          type: integer
        avg_latency:
          type: number
          format: float

    AnalyticsRelaysTransactions:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        account_id:
          type: string
        portal_application_id:
          type: string
        chain_id:
          type: string
        chain_method:
          type: string
        error_rate:
          type: number
          format: float
        cnt:
          type: integer
        avg_roundtrip_time:
          type: number
          format: float
    AnalyticsRelaysErrors:
      type: object
      properties:
        from:
          type: string
          format: date
        to:
          type: string
          format: date
        account_id:
          type: string
        portal_application_id:
          type: string
        chain_id:
          type: string
        chain_method:
          type: string
        error_type:
          type: string
        error_name:
          type: string
        cnt:
          type: integer
    Logs:
      type: object
      properties:
        ts:
          type: string
          format: timestamp
        portal_application_id:
          type: string
        chain_id:
          type: string
        chain_method:
          type: string
        error_type:
          type: string
        error_name:
          type: string
        error_message:
          type: string
    Response:
      type: object
      properties:
        data:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/AnalyticsRelaysAggregated"
              - $ref: "#/components/schemas/AnalyticsRelaysDaily"
              - $ref: "#/components/schemas/AnalyticsRelaysTransactions"
              - $ref: "#/components/schemas/AnalyticsRelaysErrors"
              - $ref: "#/components/schemas/Logs"

tags:
  - name: "system"
    description: "Operations related to api-server"
  - name: "user"
    description: "Operations related to individual portal users and their applications"
  - name: "product"
    description: "Operations related to the portal data as a whole"
